AxaFrance/react-toolkit

packages/Layout/header/src/Name/Name.js

https://github.com/AxaGuilDEv/react-toolkit/issues/40
https://github.com/AxaGuilDEv/react-toolkit/issues/40
Fix display name for Name component
@guillaumechervetaxa @samuel-gomez-axa 
```sh
$ npm test
```

fix(storybook): display name for Component Name

---

azure-pipelines.yml
package-lock.json
package.json
packages/help/src/Help.spec.js
packages/help/src/__snapshots__/Help.spec.js.snap
packages/popover/README.md
packages/popover/package-lock.json
packages/popover/package.json
packages/popover/package.json.lerna_backup
packages/popover/src/PopoverBase.js
storybook/addons/package-lock.json
storybook/storybook/package-lock.json

#17 
#17 
This issue is due to the upgrade of react-popper which is in 1.3.3. Toolkit popover is in 0.8.3 but pull the ^1.12.9 of  react-popper and use Arrow and Target  component which are not available in react-popper up to 1.x.x
```sh
$ npm test
```

feat: migrate popover @0.x to @1.x

---

packages/popover/src/Popover.js

https://github.com/AxaGuilDEv/react-toolkit/issues/193
Popover not working with onclick mode (nothing appens)
@guillaumechervet 
@samuel-gomez-axa 
@barry-thierno

fix(popover): not working with onclick mode

---

packages/Form/Input/file/src/File.js
packages/Form/Input/file/src/FileTable.js
packages/Form/Input/file/src/__snapshots__/FileTable.spec.js.snap

- Warning properties on DOM Element input file
- Errors input doesn't display if no values

fix: omit props and display errors

---

package-lock.json
packages/restitution/src/HeaderRestitution.tsx
packages/restitution/src/Restitution.spec.tsx
storybook/storybook/src/packages/restitution/src/Restitution.stories.js

#346 
The `HeaderRestitution` component has a property `titleLeft` which add some content at the right of the restitution header.
This property should be called `rightTitle` as the content is displayed at the right.
@guillaumechervet

refactor(restitution) Change titleLeft to rightTitle prop in HeaderRestitution

---

packages/popover/src/popover.scss

`When using the help button component beside another form component (text input for exemple), the popover appears below the input frame, with a default width that makes it hardly readable.`
`You can add @samuel-gomez-axa @guillaumechervet  @guillaumechervetaxa `
```sh
$ npm test
```

feat(ToolkitCore): Le texte ne passe plus en dessous des inputs.

---

storybook/design-system/src/components/colors/Color.pug
storybook/design-system/src/components/colors/Colors.pug

When doing a `git checkout` of the project we have the following warning
```
warning: the following paths have collided (e.g. case-sensitive paths
on a case-insensitive filesystem) and only one from the same
colliding group is in the working tree:
'storybook/design-system/src/components/colors/Color.pug'
'storybook/design-system/src/components/colors/color.pug'
'storybook/design-system/src/components/colors/Colors.pug'
'storybook/design-system/src/components/colors/colors.pug'
```
@samuel-gomez-axa 
```sh
$ npm test
```

fix: remove duplicated files

---

packages/Form/Input/number/src/Number.spec.js
packages/Form/Input/number/src/NumberHelper.js

fix(NumberInput): isValidNumber for support zero value in the component numberInput

---

CONTRIBUTING.md
packages/Form/core/src/form.scss
storybook/storybook/src/packages/Form/Demo/Form.js
storybook/storybook/src/packages/Form/Input/checkbox/src/CheckboxInput.stories.js
storybook/storybook/src/packages/Form/Input/choice/src/ChoiceInput.stories.js
storybook/storybook/src/packages/Form/Input/date-phone/src/DatePhoneInput.stories.js
storybook/storybook/src/packages/Form/Input/date/src/DateInput.stories.js
storybook/storybook/src/packages/Form/Input/file/src/FileInput.stories.js
storybook/storybook/src/packages/Form/Input/number/src/NumberInput.stories.js
storybook/storybook/src/packages/Form/Input/pass/src/PassInput.stories.js
storybook/storybook/src/packages/Form/Input/radio/src/RadioInput.stories.js
storybook/storybook/src/packages/Form/Input/select-multi/src/MultiSelectInput.stories.js
storybook/storybook/src/packages/Form/Input/select/src/SelectInput.stories.js
storybook/storybook/src/packages/Form/Input/slider/src/Slider.stories.js
storybook/storybook/src/packages/Form/Input/switch/src/Switch.stories.js
storybook/storybook/src/packages/Form/Input/text/src/TextInput.stories.js
storybook/storybook/src/packages/Form/Input/textarea/src/Textarea.stories.js

Automatically add a red star on label of required fields.
Sample render (from storybook):
To migrate from old manual star to new automatic red star:
```diff
<TextInput
-  label="My label *"
+  label="My label"
+  classModifier="required"
{...otherProps}
</TextInput>
```
cc @guillaume-chervet @samuel-gomez  @youf-olivier

feat(react-toolkit-form): add a red star on label of required fields

---

packages/Form/summary/package.json
packages/Layout/footer/package.json
packages/Modal/default/package.json
packages/action/package.json
packages/alert/package.json
packages/badge/package.json
packages/button/package.json
packages/core/package.json
packages/icon/package.json
packages/restitution/package.json
packages/table/package.json
packages/tabs/package.json
packages/title/package.json

Add types declaration files to `package.json` for packages written in TypeScript.
People using TypeScript can remove their declaration for components from the following packages:
- @axa-fr/react-toolkit-action
- @axa-fr/react-toolkit-alert
- @axa-fr/react-toolkit-badge
- @axa-fr/react-toolkit-button
- @axa-fr/react-toolkit-core
- @axa-fr/react-toolkit-form-summary
- @axa-fr/react-toolkit-icon
- @axa-fr/react-toolkit-layout-footer
- @axa-fr/react-toolkit-modal-default
- @axa-fr/react-toolkit-restitution
- @axa-fr/react-toolkit-table
- @axa-fr/react-toolkit-tabs
- @axa-fr/react-toolkit-title
@samuel-gomez @guillaumechervet @youf-olivier

build(TypeScript): expose typings

---

packages/Form/core/src/FieldForm.js

Remove use of `componentWillUpdate` in FieldForm to remove this warning message:
```
react_devtools_backend.js:6 Warning: componentWillReceiveProps has been renamed, and is not recommended for use. See https://fb.me/react-unsafe-component-lifecycles for details.
* Move data fetching code or side effects to componentDidUpdate.
* If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://fb.me/react-derived-state
* Rename componentWillReceiveProps to UNSAFE_componentWillReceiveProps to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` …
```

refactor(react-toolkit-form): remove use of componentWillUpdate

---

packages/Form/core/src/FieldForm.js

Rollback #613 because `forceDisplayMessage` didn't work anymore
I used the UNSAFE version of componentWillReceiveProps instead of removing it.
We need to be able to create a unit test but I don't know how...

refactor(react-toolkit-form): rollback remove use of componentWillUpdate

---

examples/demo/package.json
package-lock.json
package.json
packages/Form/Input/select-multi/package-lock.json
packages/Form/Input/select-multi/package.json
packages/Form/Input/select-multi/src/MultiSelect.js
packages/Form/Input/select-multi/src/__snapshots__/MultiSelect.spec.js.snap
packages/Form/Input/select-multi/src/__snapshots__/MultiSelectInput.spec.js.snap
storybook/storybook/package.json

Bump react-select to latest version.
I followed the [migration guide](https://github.com/JedWatson/react-select/issues/3585).
The only change for us is the new import for the async react-select component.
@guillaume-chervet @samuel-gomez @youf-olivier

build: bump react-select to version 3.1.0

---

packages/Layout/header/src/Title/Title.js
packages/Layout/header/src/Title/Title.spec.js
packages/Layout/header/src/Title/__snapshots__/Title.spec.js.snap
packages/Layout/header/src/Title/title-bar.scss
storybook/storybook/src/packages/Layout/header/src/Title/src/Title.stories.js

Before : 
After
We use the burger menu only if : 
- We are in small display
- The togglemenu function is passed in props
https://axaguildev.github.io/react-toolkit/latest/design/molecules/title-bar/

fix(title): Fix burger menu in plain display

---

packages/help/src/__snapshots__/Help.spec.js.snap
packages/popover/src/Popover.js
packages/popover/src/popover.scss

Fix a11y issue on the popover when "click" mode:
- Visible, non-interactive elements with click handlers must have at least one keyboard listener jsx-a11y/click-events-have-key-events 
- Static HTML elements with event handlers require a role jsx-a11y/no-static-element-interactions

feat(popover): fix a11y for popover

---

packages/Form/Input/choice/src/Choice.spec.js
packages/Form/Input/choice/src/ChoiceInput.js
packages/Form/Input/choice/src/__snapshots__/Choice.spec.js.snap

When the ChoiceInput options don't have an id, use the id that we pass to create one (concatenate it with the index) instead of always generating a new one.
It allows to use snapshots with this component.
Fixes #616

feat(form-input-choice): use the id instead of generating a new one

---

packages/Layout/footer/src/FooterCore.tsx

Use the current year as default value in the copyright of the footer instead of a fixed value (2018).
There is no need to override it by default.
Fixes #601

feat(layout-footer): use current year as default in copyright

---

packages/Form/Input/radio/src/Radio.js
packages/Form/Input/radio/src/RadioInput.spec.js
packages/Form/Input/radio/src/__snapshots__/RadioInput.spec.js.snap

Send the `id` of the radio button on change.
Fixes #633

feat(form-input-radio) send id on change

---

packages/help/src/__snapshots__/Help.spec.js.snap
packages/popover/src/Popover.js
packages/popover/src/PopoverBase.js
packages/popover/src/popover.scss

Change the way we detect that we click outside the popover to dismiss it to remove the `stopPropagation` on body's event `click`.
Note, I also fixed:
- the arrow position
- unused props
Fixes #643

fix(popover): popover prevents click action on the page

---

packages/Form/steps/src/StepLink.js
packages/Layout/header/src/NavBar/NavBar.js
packages/Layout/header/src/NavBar/NavBarBase.js

onClick prop was required on some component. If you know other useless required prop, add them on this PR.
```sh
$ npm test
```

feat: onClick is no longer required on navbar and steplink

---

packages/Layout/footer/README.md
packages/Layout/footer/src/Footer.ts
packages/Layout/footer/src/FooterCore.tsx
storybook/storybook/src/packages/Layout/footer/src/Footer.stories.js

#77 
Logo link in the footer #77
```sh
$ npm test
```

feat: add props to footer component to hide icon

---

packages/tabs/src/Tabs.spec.tsx
packages/tabs/src/TabsCore.spec.tsx
packages/tabs/src/TabsCore.tsx
storybook/storybook/src/packages/tabs/src/Tabs.stories.js

Unable to activate index upper than zero (default) when init Tabs component
It is impossible to display particular tab other than 0 index when showing Tabs component
```sh
$ npm test
```

fix(tabs): init tabs with custom active index other than zero

---

packages/alert/src/AlertCore.tsx
packages/alert/src/__snapshots__/Alert.spec.tsx.snap
packages/alert/src/__snapshots__/AlertCore.spec.tsx.snap
packages/alert/src/__snapshots__/AlertWithType.spec.tsx.snap

Add the role Attribute to the alert component to improve accessibility and testing.
(The snapshot for help had updated, it's about a little modification in the commit f4a7ac2a5b9ee78ce2a75efbdb1d662c9aadacdc)

feat(alert): add role attribute

---

packages/table/src/Pager/pager.scss
storybook/storybook/src/packages/table/src/Pager/Pager.stories.js

#689 
When the table had 4-digit number of pages, the active page was truncated and blue bullet not centered
@samuel-gomez @guillaumechervet @youf-olivier @LeGrandKhan

fix(table-pager): add flexible width when active page number is large

---

CONTRIBUTING.md
package.json

Drop support of Node.js version not supported our dependencies:
- must be a LTS version
- jest minimum support is [10.14.2](https://github.com/facebook/jest/blob/master/package.json#L134)
Fixes #706

build: drop support of old Node.js versions

---

packages/Form/Input/date/src/datepicker.scss

When you use the Form/Input/Date component, you are not able to click on the glyphicon in the input field. You have to click somewhere else in the input field.
@gcruchon @guillaumechervet @guillaume-chervet @guillaumechervetaxa @samuel-gomez @samuel-gomez-axa @Cleclemi28 @youf-olivier @Gparquet
```sh
$ npm test
```

fix(Form/Input/Date): Make the glyphicon clickable

---

packages/collapse/src/Accordion.tsx
packages/collapse/src/Collapse.stories.tsx

Fix #721 
Accordion rewrites onToggle for CollapseCardBase, a possible solution is to add a callback function props  that would be called after onToggle
```sh
$ npm test
```

feat(collapse): added onToggleCallback prop on CollapseCardBase

---

package-lock.json
package.json

When we run `npm test -- --coverage` we have the following issue:
```
packages/Modal/default/src/Div.tsx:8:46 - error TS2322: Type '{ ref?: LegacyRef<HTMLDivElement>; key?: Key; defaultChecked?: boolean; defaultValue?: string | number | readonly string[]; suppressContentEditableWarning?: boolean; ... 250 more ...; onTransitionEndCapture?: (event: TransitionEvent<...>) => void; }' is not assignable to type 'DetailedHTMLProps<HTMLAttributes<HTMLDivElement>, HTMLDivElement>'.
Type '{ ref?: LegacyRef<HTMLDivElement>; key?: Key; defaultChecked?: boolean; defaultValue?: string | number | readonly string[]; suppressContentEditableWarning?: boolean; ... 250 more ...; onTransitionEndCapture?: (event: TransitionEvent<...>) => void; }' is not assignable to type 'HTMLAttributes<HTMLDivElement>'.
The …
```

build: force csstype to version ^3.0.4

---

.prettierignore

Exclude `lerna.json` from Prettier check to fix CI on master.

build: exclude lerna from prettier check

---

azure-pipelines.yml

Fix issue on CI
```
Job Job: Step specifies condition and(succeeded(), notIn(variables['Npm.Publish.Version'], 'none', 'premajor', 'preminor', 'prepatch', 'prerelease') which is not valid. Reason: Unclosed function: 'and'. Located at position 1 within expression: and(succeeded(), notIn(variables['Npm.Publish.Version'], 'none', 'premajor', 'preminor', 'prepatch', 'prerelease'). For more help, refer to https://go.microsoft.com/fwlink/?linkid=842996
```

build: fix CI job condition

---

packages/Form/Input/text/src/TextInput.stories.js
packages/Form/core/src/Field.js
packages/Form/core/src/FieldConstants.js

Simple use Case : Permettre d'ajouter plus que du texte dans les labels.
Cf exemple ajouté dans le storybook : 
Pour le moment on peut le faire mais ça log un warning.

feat: allow react element on inputs labels

---

packages/Form/Input/file/package.json
packages/Form/Input/file/src/File.js

Fixes #796 
**Description**
I've updated the react-dropzone dependency for the FileInput component.
The update had an impact on the component so I did a little refacto.
**Question**
I have a question about the _...otherProps_, are they really necessary ? And if so, what are they used for in the case of this component?

Update react-dropzone dependency

---

packages/button/src/button.scss

[Button] font-weight : 400

---

packages/Form/Input/file/src/file.scss

feat(FileInput): reduce InputFile browse button width

---

packages/collapse/src/Body.tsx

Fix #862 
La max-height  a de l'importance que dans l'unique but de faire fonctionner l'animation lors de l'ouverture du collapse

[Collapse] max-height à 100vh quand ouvert

---

MIGRATION.md

I found a few issues with this guide, and this is my proposition to fix them.
The sentence with the dynamic import was weird, and CRA has it by default. Since it's most people's tool, i feel it's better to highlight that, rather than throwing a generic "make sure your tool does the job"
> param which allow to specify the way to display value in viewvalue and in the field
Still not sure what this was meant to say, especially the "viewvalue and in the field" part. But at least the sence feels less awkward to read in my opinion.

docs(migration): fixed a few typos and phrasings

---

package-lock.json
package.json
packages/Form/Input/card/src/card.scss
packages/core/src/common/scss/_custom-af.scss
packages/core/src/common/scss/_functions.scss
packages/core/src/common/scss/_variables.scss

Résolution de l'issue 992, l'avertissement n'apparait plus car le / pour la division n'est plus utilisé.
utilisation de la migration Automatique proposée par [sass](https://sass-lang.com/documentation/breaking-changes/slash-div#automatic-migration)
Description of the issue
Division using / are deprecated and going to be removed in dart sass 2.0.0
When you build an app with sass 1.35.1, you get a warning saying : "DEPRECATION WARNING: Using / for division is deprecated and will be removed in Dart Sass 2.0.0."
This issue appears mainly with the file @axa-fr\react-toolkit-core\src\common\scss_variables.scss

fix(sass): fixing issue #922

---

packages/restitution/README.md
packages/restitution/src/Restitution.stories.tsx
packages/restitution/src/Restitution.tsx
packages/restitution/src/__tests__/Restitution.spec.tsx
packages/restitution/src/__tests__/__snapshots__/Restitution.spec.tsx.snap

https://github.com/AxaGuilDEv/react-toolkit/issues/945
```sh
$ npm test
```

feat(Restitution): allow ReactNode in value

---

packages/restitution/README.md
packages/restitution/src/Restitution.stories.tsx
packages/restitution/src/Restitution.tsx
packages/restitution/src/RestitutionList.tsx
packages/restitution/src/__tests__/Restitution.spec.tsx
packages/restitution/src/__tests__/__snapshots__/Restitution.spec.tsx.snap
packages/restitution/src/index.ts

Close #949 
Following allowing ReactNode in value of Restitution (https://github.com/AxaGuilDEv/react-toolkit/issues/945) properties value and values overlap.
The goal is now to keep only one of the two property.
For example, we can keep value and delete values but export the RestitutionValues component that is used when values is passed in order to let the consumer use that component as children of Restitution.
@samuel-gomez

refactor(Restitution): add children property and export RestitutionList

---

packages/Form/summary/README.md
packages/Form/summary/src/Summary.stories.tsx
packages/Form/summary/src/Summary.tsx
packages/Form/summary/src/__tests__/Summary.spec.tsx
packages/Form/summary/src/__tests__/__snapshots__/Summary.spec.tsx.snap

`[Issue](https://github.com/AxaGuilDEv/react-toolkit/issues/975)`
`The summary form component allows only an array of string for the messages to be displayed.
We would like to extend that with ReactNode in order to pass more complex messages (with links for example).`
@arnaudforaison

feat(Summary): allow ReactNode in messages array

---

packages/restitution/src/HeaderRestitution.tsx
packages/restitution/src/__tests__/Restitution.spec.tsx
packages/restitution/src/__tests__/__snapshots__/Restitution.spec.tsx.snap

The outgoing type for HeaderRestitution was the base type and not the enhanced one with classModifier.
```sh
$ npm test
```
```ts
interface HeaderRestitutionProps {
className?: string;
title: React.ReactNode;
subtitle?: React.ReactNode;
rightTitle?: React.ReactNode;
classModifier?: string | null;
defaultClassName?: string | null;
}
const HeaderRestitutionFixed: (props: HeaderRestitutionProps) => JSX.Element = HeaderRestitution as never;
const MyComponent = () => (
<HeaderRestitutionFixed
classModifier="stackedRight" // no error
/>
);
```

fix(Restitution): fixed HeaderRestitution's type missing classModifier

---

packages/Form/Input/select/src/SelectInput.tsx

When you use `<SelectInput />` component without id prop, there is an id consistency problem :
1 - `SelectInput.tsx` code will generate a new id with `useId` because prop is empty
2 - `Select.tsx` code will generate a new id with `useId` because the previous generated id is not given to this component

fix(SelectInput): id consistency problem when empty prop value

---

.gitignore
CONTRIBUTING.md
packages/all/.gitignore
packages/all/package.json

esm build files were not present in the 2.0.0 npm package, meaning we could not get tree-shaking or making the package unsuable in esbuild, vite & friends.
@arnaudforaison

Fixed esm build for package all

---

packages/Layout/header/src/NavBar/NavBarBase.tsx
packages/Layout/header/src/__tests__/NavbarItem.spec.tsx
packages/Layout/header/src/__tests__/NavbarItemBase.spec.tsx

fix #1004 
- mobile menu not appear
- fix some accessibilty issues
@korger-johan @arnaudforaison 
```sh
$ npm test
```

fix(menu): mobile

---

.storybook/main.js
.storybook/preview.js
package-lock.json
package.json
packages/Modal/boolean/src/ModalBoolean.stories.tsx
packages/all/package.json
packages/all/src/help-info.ts
packages/all/src/index.ts
packages/help/src/Help.tsx
packages/helpinfo/README.md
packages/helpinfo/package.json
packages/helpinfo/src/HelpInfo.stories.tsx
packages/helpinfo/src/HelpInfo.tsx
packages/helpinfo/src/__tests__/HelpInfo.spec.tsx
packages/helpinfo/src/help-info.scss
packages/helpinfo/src/index.ts
packages/helpinfo/tsconfig-cjs.json
packages/helpinfo/tsconfig.json

fix #1010 
- Create a new categorie for high level components
- Add a wrapper infobulle component (based on @axa-fr/react-toolkit-popover like Help component)
this component could wrap any component
```sh
$ npm test
```

feat(helpinfo): add new high level component

---

packages/Form/Input/select/src/Select.stories.tsx
packages/Form/Input/select/src/Select.tsx
packages/Form/Input/select/src/SelectBase.tsx
packages/Form/Input/select/src/__tests__/Select.spec.tsx
packages/Form/Input/select/src/__tests__/__snapshots__/Select.spec.tsx.snap

fix #1012 
fix #1008 
Fix for apply classModifier on select field
Fix for display placeholder with forceDisplayPlaceholder
@SamuelHsn @johankorger 
```sh
$ npm test
```

fix(select): classModifier and forceDisplayPlaceholder

---

.storybook/main.js
packages/table/src/Header.tsx
packages/table/src/Items/Items.stories.tsx
packages/table/src/Pager/Pager.stories.tsx
packages/table/src/Pager/pager.scss
packages/table/src/Paging/Paging.stories.tsx
packages/table/src/Paging/Paging.tsx
packages/table/src/table.scss

fix #918 
- group stories in Table directory
- add style for mobile
- fix border-radius for long number
```sh
$ npm test
```

fix(table): stories, items and mobile style

---

packages/Form/Input/number/src/NumberInput.stories.tsx

Impossible to type a minus sign in a NumberInput 
#999
[`link to related issue`](https://github.com/AxaFrance/react-toolkit/issues/999)
`On a NumberInput, when you can type a minus sign the first time, but if you clear the input and you try again to type the minus sign, nothing happen and the value prop contains NaN,it was a bug that affected only the Storybook, the bug is not present in the component`
@johnmeunier @arnaudforaison

test(NumberInput): type a minus sign in a NumberInput

---

packages/Form/Input/checkbox/src/checkbox.scss
packages/Form/Input/choice/src/radio.scss
packages/Form/Input/radio/src/radio.scss

https://github.com/AxaFrance/react-toolkit/issues/1039
@arnaudforaison @samuel-gomez @buddyvegas

fix(accessibility): allow focus on radio inputs

---

packages/Form/Input/checkbox/README.md
packages/Form/Input/checkbox/src/CheckboxInput.tsx
packages/Form/Input/checkbox/src/CheckboxItem.tsx
packages/Form/Input/choice/src/ChoiceInput.stories.tsx
packages/Form/Input/choice/src/ChoiceInput.tsx
packages/Form/Input/choice/src/__tests__/Choice.spec.tsx
packages/Form/Input/choice/src/__tests__/__snapshots__/Choice.spec.tsx.snap
packages/Form/Input/date/src/Date.tsx
packages/Form/Input/file/src/File.tsx
packages/Form/Input/file/src/FileInput.tsx
packages/Form/Input/file/src/__tests__/__snapshots__/File.spec.tsx.snap
packages/Form/Input/file/src/__tests__/__snapshots__/FileInput.spec.tsx.snap
packages/Form/Input/file/src/file.scss
packages/Form/Input/number/src/Number.tsx
packages/Form/Input/pass/src/Pass.tsx
packages/Form/Input/radio/src/RadioInput.tsx
packages/Form/Input/radio/src/RadioItem.tsx
packages/Form/Input/select/src/Select.tsx
packages/Form/Input/select/src/SelectBase.tsx
packages/Form/Input/slider/src/Slider.tsx
packages/Form/Input/switch/src/SwitchItem.tsx
packages/Form/Input/text/src/Text.tsx
packages/Form/Input/text/src/TextInput.stories.tsx
packages/Form/Input/textarea/src/Textarea.tsx

https://github.com/AxaFrance/react-toolkit/issues/1044
@arnaudforaison @samuel-gomez @buddyvegas

fix(accessibility): add attribute required based on classModifier

---

packages/action/src/button.scss
packages/button/src/button.scss
packages/help/src/Help.tsx
packages/help/src/__tests__/Help.spec.tsx
packages/help/src/help-custom.scss

Resolve [981](https://github.com/AxaGuilDEv/react-toolkit/issues/981)

feat(Help): add help button content in props

---

packages/Form/Input/file/src/File.tsx
packages/Form/Input/file/src/__tests__/FileLine.spec.tsx
packages/Form/Input/file/src/__tests__/FileTable.spec.tsx

[1034](https://github.com/AxaFrance/react-toolkit/issues/1034)
@arnaudforaison @samuel-gomez

fix(File): file prototype properties are lost with spread operator

---

packages/alert/src/alert.scss

Fix #995
The red vertical strip of the Alert component may be inconsistent depending of the content.
None.

feat(design): fix some issues when a lot of texts is present

---

packages/helpinfo/src/HelpInfo.stories.tsx
packages/helpinfo/src/HelpInfo.tsx

[1074](https://github.com/AxaFrance/react-toolkit/issues/1074)

fix: remove require of helpinfo css to stop causing crash from vite/vitest apps

---

MIGRATION.md

Update migration guide for 2.1.0 version

docs: add migration documentation to 2.1.x version

---

MIGRATION.md
README.md

Remove use of component folder inside toolkit-all in documentation

docs: modify README for components's imports (don't use component folder inside toolkit-all)

---

packages/button/README.md
packages/button/src/Button.stories.tsx
packages/button/src/button.scss

https://github.com/AxaFrance/react-toolkit/issues/1098
By using the aria-disabled attribute we should have the same style as the disabled one.

fix: use same style for aria-disabled buttons as disabled

---

packages/all/src/form-core.ts

https://github.com/AxaFrance/react-toolkit/issues/1090
I followed this suggested correction : https://github.com/AxaFrance/react-toolkit/issues/1090#issuecomment-1836127530
@samuel-gomez @MartinWeb 
```sh
$ npm test
```

feat(all form-core): add FieldForm in form-core export file

---

packages/collapse/src/CollapseCard.tsx

https://github.com/AxaFrance/react-toolkit/issues/1058
The browser lost focus of the input because the children's ID was regenerated at each rerender. (if you had not defined a custom id)
I had to rename `useId` to `getId` because each function with `use` is considered has React Hook and we can't put a React Hook in a `useMemo`.
@samuel-gomez @MartinWeb 
```sh
$ npm test
```

fix(collapse): stop to regenerate id at each rerender

---

packages/Form/Input/file/src/__tests__/__snapshots__/FileLine.spec.tsx.snap
packages/help/src/Help.stories.tsx
packages/help/src/Help.tsx
packages/help/src/help-custom.scss
packages/helpinfo/src/HelpInfo.stories.tsx
packages/helpinfo/src/help-info.scss
packages/popover/src/Popover.tsx
packages/popover/src/__tests__/Popover.spec.tsx
packages/popover/src/help-custom.scss
packages/popover/src/popover.scss

https://github.com/AxaFrance/react-toolkit/issues/1080
I removed the second button to improve accessibility.
It wasn't blocking the `onKeyPress` but the condition which required your cursor to be over the button to use the `onKeyPress`.
I changed a little bit the UX :
```
Activated when :
- button click / button hover
- button hover + button focus+ press any key
Deactivated when :
- button click / no button hover
- click away from button
- button hover+ button focus+ press any key
- lose button focus
```
```
Activated when :
- button click / button hover
- button focus + press "Enter" key
Deactivated when :
- button click / no button hover
- click away from button
- button focus + press "Enter" key
- lose button focus
```
I had `role="button"` on PopoverOver wrapper to be focusable.
I've …

fix(popover/help/helpinfo): help button contains two button, it desactivate the default onKeyPress 

---

packages/Layout/header/README.md
packages/Layout/header/src/Title/Title.stories.tsx
packages/Layout/header/src/Title/Title.tsx
packages/Layout/header/src/Title/title-bar.scss
packages/Layout/header/src/__tests__/Title.spec.tsx
packages/Layout/header/src/__tests__/__snapshots__/Title.spec.tsx.snap

https://github.com/AxaFrance/react-toolkit/issues/1112

feat(header): make title-bar sticky by default

---

MIGRATION.md
packages/title/src/title.scss

fix(title): remove previous title css

---

packages/Form/steps/src/Steps.stories.tsx

Both steps stories have the same name.

fix(storybook): steps stories name

---

packages/Form/Input/switch/src/Switch.stories.tsx
packages/Form/Input/switch/src/Switch.tsx
packages/Form/Input/switch/src/SwitchInput.tsx

feat: mark switch as deprecated

---

CONTRIBUTING.md
MIGRATION.md

The pull request addresses missing information and corrects spelling errors in the migration and contribution documentation
```sh
$ npm test
```

docs: update documentation and correction of misspelled words

---

README.md

No documentation for mandatory steps before integration the package
https://github.com/AxaFrance/react-toolkit/issues/1190
@MartinWeb

docs: add sass and bootstrap setup in the documentation

---

packages/Form/Input/select/src/Select.tsx

https://github.com/AxaFrance/react-toolkit/issues/1188
`Remove "- Select -" option when a default value is defined`

fix(Select): remove select option when defaultValue is defined

---

packages/Form/steps/src/Steps.stories.tsx
packages/Form/steps/src/step-form.scss

Mark old step form design as deprecated.
It shouldn't be used anymore.

feat: mark old step form design as deprecated

---

MIGRATION.md

docs: add migration documentation for 3.0.0 version
