AxaFrance/react-toolkit

scripts/twitter.js

fix(twitter) update message

---

packages/badge/README.md

doc: Adding imports documentation for badge

---

scripts/publish-docs.js

@guillaumechervetaxa this code is not tested yet can you please read it carefully

fix(demo) update publish script to change the baseUrl of the previous version

---

packages/Form/Input/slider/src/Slider.js
packages/Form/Input/slider/src/Slider.spec.js
packages/Form/Input/slider/src/SliderInput.js
packages/Form/Input/slider/src/__snapshots__/Slider.spec.js.snap
packages/Form/Input/slider/src/__snapshots__/SliderInput.spec.js.snap
packages/Form/Input/slider/src/slider.scss
storybook/storybook/src/packages/Form/Input/Slider.stories.js

feat(slider) add slider wrapped

---

package-lock.json
package.json
scripts/tasks/all.js
storybook/design-system/package.json

#205 
Update lerna version and fix gulp sass imports
@guillaumechervet

chore: update lerna and change dist to src imports SASS

---

.gitignore
.vscode/settings.json
scripts/publish-docs.js

fix(publish) design system website

---

storybook/design-system/gulpfile.babel.js/config.js
storybook/design-system/gulpfile.babel.js/index.js
storybook/design-system/gulpfile.babel.js/pug.js
storybook/design-system/gulpfile.babel.js/sass.js
storybook/design-system/src/assets/sprite/sprite.symbol.html
storybook/design-system/src/commons/layout.pug
storybook/design-system/src/components/menu/menuitem.pug
storybook/design-system/src/data/base.json

fix the menu design system baseurl
@guillaumechervet

fix(DS): baseurl links on build

---

packages/Form/Input/radio/src/RadioInput.js
packages/popover/src/popover.scss
storybook/storybook/src/packages/Form/Input/radio/src/RadioInput.stories.js

Miss children for radio input component
@guillaumechervet

feat: add children for radio input form component

---

storybook/design-system/src/components/colors/color.pug
storybook/design-system/src/components/colors/colors.pug

Fix build design system
@guillaumechervetaxa

fix(design-system) lowercase colors.pug

---

package-lock.json
packages/Form/Input/select/src/Select.js
packages/Form/Input/select/src/SelectBase.js
packages/Form/Input/select/src/SelectInput.js
storybook/storybook/src/packages/Form/Input/select/src/SelectInput.stories.js

#402 
Add forceDisplayPlaceholder props on select input
@guillaumechervetaxa @guillaumechervet 
```sh
$ npm test
```

fix(input select) : add prop to force display placeholder - #402

---

packages/Form/Input/date-phone/src/DatePhone.js

fix(date-phone): normalize viewValue with date

---

scripts/config.js
scripts/style.js

#666
Please before valid this PR, clone this branch and test the installation

fix(css): restore legacy boostrap css files - #666

---

storybook/design-system/gulpfile.babel.js/index.js

problem generation contributors's page

fix(pug): contributors page production build

---

CONTRIBUTING.md

I fixed the treeview in the contributing.md
@samuel-gomez

docs: fixed storybook treeview

---

packages/Layout/header/src/NavBar/nav.scss

NavBar UX guidelines fixes

---

packages/Layout/footer/src/footer.scss
packages/Layout/header/src/Infos/infos.scss
packages/Layout/header/src/Logo/logo.scss
packages/Layout/header/src/Name/Name.js
packages/Layout/header/src/Name/__snapshots__/Name.spec.js.snap
packages/Layout/header/src/Name/name.scss
packages/Layout/header/src/NavBar/nav.scss
packages/Layout/header/src/Title/title-bar.scss
packages/core/src/common/scss/_custom-af-colorsvariables.scss
packages/core/src/common/scss/colorsList.js

Apply fix guidelines

---

packages/Layout/footer/src/Footer.ts
packages/Modal/default/src/Header.ts
packages/action/src/index.ts
packages/alert/src/Alert.ts
packages/alert/src/AlertWithType.ts
packages/badge/src/index.ts
packages/collapse/src/Constant.ts
packages/core/src/ClassManager.ts
packages/core/src/compose.ts
packages/core/src/index.ts
packages/loader/src/index.ts
packages/restitution/src/index.ts
packages/title/src/index.ts

Fixes Tslint warnings and errors.
Resolves CI errors on #728

style: fix tslint error

---

packages/Form/Input/text/src/inputtext.scss

feat(form-input-text): fix design issues

---

.storybook/manager.js

Fix #769 
Changing brandUrl to match the new design system URL.
@xballoy @samuel-gomez @arnaudforaison @guillaumechervet @youf-olivier

fix(storybook): change the brandUrl to match the spirit of the project

---

azure-pipelines.yml

Ignore pipeline tasks of publishing when it's a pre version

Ignore publish for pre version

---

jest.config.json
package-lock.json
packages/Form/Input/choice/src/__snapshots__/Choice.spec.js.snap
packages/Form/Input/radio/src/__snapshots__/RadioInput.spec.js.snap
packages/core/package.json
packages/core/src/ClassManager.spec.ts
packages/core/src/ClassManager.ts
packages/core/src/InputManager.spec.ts
packages/core/src/InputManager.ts
packages/core/src/PropsManager.spec.ts
packages/core/src/PropsManager.ts

- Add unit tests on `react-toolkit-core`
- Bump dependencies for `react-toolkit-core`
I found an issue in `InputManager.getFirstId`, it was always returning an empty string. That's why 4 snapshots have been updated.

test(core): add tests

---

package-lock.json
package.json

Related issue #764
Version
"version":"1.3.23"
Reference to the issue
Here you can add link to related issue
Description of the issue
Expected
Additional Details
legacy boostrap with reboot.css and grid.css
Person(s) for reviewing proposed changes
@samuel-gomez @samuel-gomez-axa @xballoy

fix(style): downgrade Bootstrap version

---

packages/Form/Input/slider/package.json
packages/Form/Input/slider/src/Slider.js
packages/Form/Input/slider/src/Slider.stories.js

dependabot a une PR d'ouverte pour mettre à jour rc-slider, mais les breking changes cassent des choses dans notre composant donc j'ai fait les modifications dans cette PR.
L'autre PR sera automatiquement fermée quand celle-ci sera mergée.

Update rc-slider dependency

---

packages/Form/summary/package.json
packages/Layout/footer/package.json
packages/Modal/boolean/package.json
packages/Modal/default/package.json
packages/action/package.json
packages/alert/package.json
packages/badge/package.json
packages/button/package.json
packages/collapse/package.json
packages/core/package.json
packages/icon/package.json
packages/restitution/package.json
packages/table/package.json
packages/tabs/package.json
packages/title/package.json

for TS migrated packages
the target of nextjs:main is incorrect.
For those  added module target cf : https://shuheikagawa.com/blog/2017/01/05/main-jsnext-main-and-module/

fix: fix target on nextjs:main and addmodule

---

.mergify.yml

Do not automatically merge a PR via mergify when it's a breaking change.

build: do not mergify breaking change

---

azure-pipelines.yml

Afin d'avoir les releases qui respectent la nouvelle archi (master = next et release = latest)

Azure Pipeline pour les nouvelles releases

---

packages/Form/Input/select/src/SelectBase.js
packages/Form/Input/select/src/__snapshots__/Select.spec.js.snap
packages/Form/Input/select/src/select.scss

[Select] Ajout de padding & couleur du text lors d'erreur

---

packages/action/src/button.scss
packages/button/src/button.scss
packages/popover/src/popover.scss

[Help] Changement de police pour le i & ajustement padding

---

package-lock.json
packages/Form/steps/src/Step.js
packages/Form/steps/src/StepCurrent.js
packages/Form/steps/src/StepLink.js
packages/Form/steps/src/StepNoLink.js
packages/Form/steps/src/Steps.stories.js
packages/Form/steps/src/__snapshots__/Step.spec.js.snap
packages/Form/steps/src/step-form-new.scss

[Stepper] Alignement du texte & des séparateurs

---

.github/workflows/ci.yml
.github/workflows/compatibility-npm.yml

Fixes #841 
Not fix but GH-Action to check
`A GitHub action implementation to validate/check npm install / npm test (on push and PR)`
```sh
$ npm test
```

build: add github action ci

---

.storybook/main.js
package-lock.json

Certaines stories étaient oubliées par Storybook

Ajout de stories oubliées

---

CONTRIBUTING.md
docs/DEVELOPER.md

Hello,
J'avais besoin de pouvoir tester la version du toolkit dans mon projet en cours pour tester des fix ou des modifications, j'ai découvert pas mal de chose pour y arriver (merci @arnaudforaison). Je vous propose une petite mise à jour du Guide de Contribution avec le modop que j'ai suivi.
Si vous pouviez le tester de votre côté pour s'assurer qu'il n'y a pas de coquilles ça serait top 👍

[Doc] Ajout d'une section 'How to make and test a change in my context'

---

.github/workflows/publish-release.yml

Déclenche uniquement sur les tags push et pas les branches

Update du publish

---

package.json

Conflit dans le cycle de vie de lerna

Supprime script npm de version

---

packages/table/README.md

https://github.com/AxaGuilDEv/react-toolkit/issues/985
`Missing documentation for paging table component`

fix(table): update documentation for paging component

---

packages/badge/README.md

[Issue](https://github.com/AxaGuilDEv/react-toolkit/issues/1018)
@arnaudforaison @samuel-gomez @JLou

docs: update badge README

---

packages/loader/README.md
packages/loader/src/Loader.tsx
packages/loader/src/__tests__/Loader.spec.tsx

https://github.com/AxaFrance/react-toolkit/issues/1053
@arnaudforaison @samuel-gomez @JLou @buddyvegas

fix(accessibility): use alert and aria-busy for loader

---

packages/Layout/header/src/Infos/Infos.tsx

Missing key prop for each Fragment inside the Infos component.

fix(Infos): missing key in header infos

---

packages/Form/Input/checkbox/src/__tests__/__snapshots__/CheckboxInput.spec.tsx.snap
packages/Form/Input/choice/src/__tests__/__snapshots__/Choice.spec.tsx.snap
packages/Form/Input/file/src/__tests__/__snapshots__/FileInput.spec.tsx.snap
packages/Form/Input/number/src/__tests__/__snapshots__/NumberInput.spec.tsx.snap
packages/Form/Input/radio/src/RadioInput.stories.tsx
packages/Form/Input/radio/src/RadioInput.tsx
packages/Form/Input/radio/src/__tests__/__snapshots__/RadioInput.spec.tsx.snap
packages/Form/Input/select-multi/src/__tests__/__snapshots__/MultiSelect.spec.tsx.snap
packages/Form/Input/select-multi/src/__tests__/__snapshots__/MultiSelectInput.spec.tsx.snap
packages/Form/Input/select/src/__tests__/__snapshots__/Select.spec.tsx.snap
packages/Form/Input/slider/src/__tests__/__snapshots__/SliderInput.spec.tsx.snap
packages/Form/Input/switch/src/SwitchInput.tsx
packages/Form/Input/switch/src/__tests__/__snapshots__/SwitchInput.spec.tsx.snap
packages/Form/Input/text/src/__tests__/__snapshots__/TextInput.spec.tsx.snap
packages/Form/Input/textarea/src/__tests__/__snapshots__/TextareaInput.spec.tsx.snap
packages/Form/core/src/Field.tsx
packages/Form/core/src/__tests__/Field.spec.tsx
packages/Form/core/src/__tests__/__snapshots__/Field.spec.tsx.snap

https://github.com/AxaFrance/react-toolkit/issues/1041
https://github.com/AxaFrance/react-toolkit/issues/1042
@arnaudforaison @samuel-gomez @buddyvegas

fix(accessibility): add role and aria-label property to input container and remove * for input required in aria-label

---

package.json

https://github.com/AxaFrance/react-toolkit/issues/1055
@arnaudforaison @samuel-gomez @JLou

ci: fix storybook build for node 18

---

jest.config.ts
package-lock.json
package.json
packages/Form/Input/select-multi/src/__tests__/__snapshots__/MultiSelect.spec.tsx.snap
packages/Form/Input/select-multi/src/__tests__/__snapshots__/MultiSelectInput.spec.tsx.snap

https://github.com/AxaFrance/react-toolkit/issues/1060

fix(style): stop regenerating snapshot because of emotion

---

package-lock.json
package.json

https://github.com/AxaFrance/react-toolkit/issues/1059

build(deps): upgrade postcss package

---

package-lock.json
packages/all/package.json

https://github.com/AxaFrance/react-toolkit/issues/1083

chore(deps): add popperjs in package all

---

packages/core/package.json

https://github.com/AxaFrance/react-toolkit/issues/1085

fix: exports core's common folder

---

packages/title/README.md
packages/title/src/Title.stories.tsx
packages/title/src/Title.tsx
packages/title/src/__tests__/Title.spec.tsx
packages/title/src/title.scss

https://github.com/AxaFrance/react-toolkit/issues/1108
Link to the design https://6ssje8.axshare.com/?id=7w20tx&p=titre___h2&g=1

feat(title): add property to change heading level and design modifications

---

packages/Layout/header/src/Title/title-bar.scss
packages/core/src/common/scss/_custom-af-colorsvariables.scss
packages/core/src/common/scss/colorsList.js

https://github.com/AxaFrance/react-toolkit/issues/1110

fix(design): change title bar subtitle color

---

packages/Form/core/src/form.scss

https://github.com/AxaFrance/react-toolkit/issues/1116

fix(form): add space between label and required visual indication (asterix)

---

packages/Form/steps/src/Step.tsx
packages/Form/steps/src/StepDisabled.tsx
packages/Form/steps/src/__tests__/__snapshots__/Step.spec.tsx.snap
packages/Form/steps/src/step-form-new.scss

https://github.com/AxaFrance/react-toolkit/issues/1118

fix(form): change color for disabled step

---

packages/Layout/footer/src/FooterCore.tsx
packages/Layout/footer/src/__tests__/__snapshots__/Footer.spec.tsx.snap

https://github.com/AxaFrance/react-toolkit/issues/1121

refactor : add rel to footer

---

.github/CHECK_ACCESSIBILITY_ISSUE.md

Initialisation du template d'issue pour vérifier l'accessibilité

Init template de vérification d'accessibilité des composants

---

.github/ISSUE_TEMPLATE/CHECK_ACCESSIBILITY_ISSUE.md
.github/ISSUE_TEMPLATE/ISSUE_TEMPLATE.md

fix: issue template prettier

---

packages/Modal/default/src/modal.scss

fix(modal): adapt modal z-index to overlap sticky title-bar

---

packages/Form/Input/date/README.md

InputConstants doesn't exist anymore
do have a replacement for InputConstants ?

Remove InputConstants

---

.github/workflows/toolkit-sonar.yml

Tentative de fix la build Sonar en erreur

ci: fix sonar action version

---

packages/table/src/Table.stories.tsx
packages/table/src/table.scss

fix(table): use border instead of box-shadow to set th border

---

packages/restitution/src/restitution.scss

fix(restitution): change restitution header height

---

packages/Layout/header/src/HeaderTitle/title-bar.scss

feat(title): augment title bar font-weight (from normal to semibold)

---

packages/Form/Input/radio/src/RadioItem.tsx
packages/Form/Input/radio/src/__tests__/__snapshots__/Radio.spec.tsx.snap

https://github.com/AxaFrance/react-toolkit/issues/1208

fix(radio): pass disabled attribute to input
